[tool.black]
line-length = 120
target-version = ['py310']


[tool.isort]
py_version = 310
profile = "black"
line_length = 120
color_output = true
skip_gitignore = true
multi_line_output = 3
remove_redundant_aliases = true
include_trailing_comma = true